### ISSUE TITLE
Handle stdin

### ISSUE THREAD

**Issue by circuitsacul** [CircuitSacul/io#6]

**Comment by zunda-arrow** [comment]
I think stdin should be inputted as a code block after the first one
```
```python
<code goes here>
`​``
`​``
<stdin>
`​``
```
If they input the code as a file then the only code block will be used as stdin.

**Comment by circuitsacul** [comment]
You have to consider the fact that `Create Instance` exists - part of my goal with io was that you could run someone elses code block. I think it would be best if stdin defaulted to nothing, and you could use a button to create a modal with a mutliline input field for editing it.
